// replace_genY_media.js - Gen Y (90s era - DDLJ, Shaktimaan, Nokia, 90s Bollywood)
const fs = require('fs'), path = require('path');
const FILE = path.join(__dirname, 'data', 'gen_y.json');
const data = JSON.parse(fs.readFileSync(FILE, 'utf8'));
const textOnly = data.filter(q => q.type === 'text');

const W = 'https://upload.wikimedia.org/wikipedia/commons';

const imageQs = [
    { mediaUrl: `${W}/thumb/9/90/DDLJ_poster.jpg/440px-DDLJ_poster.jpg`, question: "Which 1995 Bollywood film featuring Shah Rukh Khan and Kajol became the longest-running Indian film?", options: ["Kuch Kuch Hota Hai", "Hum Dil De Chuke Sanam", "Maine Pyar Kiya", "Dilwale Dulhania Le Jayenge (DDLJ)"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/a/a9/Shah_Rukh_Khan.jpg/440px-Shah_Rukh_Khan.jpg`, question: "Which Bollywood 'King Khan' was known for iconic arms-spread pose that 90s girls swooned over?", options: ["Aamir Khan", "Salman Khan", "Hrithik Roshan", "Shah Rukh Khan"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/1/1e/Kajol_2019.jpg/440px-Kajol_2019.jpg`, question: "Which 90s Bollywood actress starred opposite SRK in DDLJ and KKHH?", options: ["Rani Mukerji", "Preity Zinta", "Juhi Chawla", "Kajol"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/8/86/Salman_Khan.jpg/440px-Salman_Khan.jpg`, question: "Who starred in 'Maine Pyar Kiya' (1989) and 'Hum Aapke Hain Koun' (1994) defining Gen Y romance?", options: ["Aamir Khan", "SRK", "Akshay Kumar", "Salman Khan"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/4/4f/Nokia_3310_blue.jpg/440px-Nokia_3310_blue.jpg`, question: "Which indestructible Nokia phone was EVERY Indian Gen Y's first mobile phone in the late 90s?", options: ["Nokia 1100", "Nokia 5110", "Nokia 8210", "Nokia 3310"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/c/c9/AR_Rahman.jpg/440px-AR_Rahman.jpg`, question: "Which composer's debut with 'Roja' (1992) transformed Indian film music forever?", options: ["Shankar-Ehsaan-Loy", "Vishal-Shekhar", "Jatin-Lalit", "A.R. Rahman"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/9/92/Madhuri_Dixit.jpg/440px-Madhuri_Dixit.jpg`, question: "'Dhak Dhak girl' who performed 'Ek Do Teen' in Tezaab (1988) — India's most popular actress in the 90s?", options: ["Sridevi", "Raveena Tandon", "Karisma Kapoor", "Madhuri Dixit"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/2/23/Pehla_Nasha.jpg/440px-Pehla_Nasha.jpg`, question: "'Pehla Nasha' was a hit song from which 1992 Aamir Khan college film about bicycle racing?", options: ["Rangeela", "Dil", "Raja Hindustani", "Jo Jeeta Wohi Sikandar"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/1/12/Sachin_Tendulkar_1990s.jpg/440px-Sachin_Tendulkar_1990s.jpg`, question: "Which Indian cricketer was called the 'God of Cricket' and scored his desert storm century in 1998 at Sharjah?", options: ["Rahul Dravid", "Sourav Ganguly", "VVS Laxman", "Sachin Tendulkar"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/c/c8/Sourav_Ganguly_Natwest.jpg/440px-Sourav_Ganguly_Natwest.jpg`, question: "Which Indian cricket captain took his shirt off at Lord's balcony after India's 2002 NatWest series win?", options: ["MS Dhoni", "Sachin Tendulkar", "Rahul Dravid", "Sourav Ganguly"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/5/5e/Sonu_Nigam.jpg/440px-Sonu_Nigam.jpg`, question: "Which 90s singer with hits like 'Deewana' became India's leading male voice replacing Kumar Sanu?", options: ["Udit Narayan", "Abhijeet", "KK", "Sonu Nigam"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/7/7b/Udit_Narayan.jpg/440px-Udit_Narayan.jpg`, question: "Which Nepali-origin playback singer voiced Shah Rukh Khan's songs in 90s films?", options: ["Sonu Nigam", "Kumar Sanu", "Abhijeet", "Udit Narayan"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/d/d4/Daler_Mehndi.jpg/440px-Daler_Mehndi.jpg`, question: "Which Punjabi pop singer with turban and dhol beats gave 'Bolo Ta Ra Ra' and 'Tunak Tunak Tun'?", options: ["Hans Raj Hans", "Gurdas Maan", "Jazzy B", "Daler Mehndi"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/0/0f/Lucky_Ali.jpg/440px-Lucky_Ali.jpg`, question: "Which 90s Indian singer known for 'O Sanam' and 'Ek Pal Ka Jeena' blended indie with Bollywood?", options: ["Shaan", "Mohit Chauhan", "KK", "Lucky Ali"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/3/3a/Cartoon_Network_logo.svg/320px-Cartoon_Network_logo.svg.png`, question: "Which cartoon channel replaced Doordarshan as every Gen Y kid's TV channel in the mid-90s?", options: ["Pogo", "Nickelodeon", "Disney Channel", "Cartoon Network"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/a/a5/Shaktimaan.jpg/440px-Shaktimaan.jpg`, question: "India's own superhero with a spinning transformation sequence — which Doordarshan show?", options: ["Flying Jatt", "Inspector Vikram", "Super Commander Dhruv", "Shaktimaan"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/4/47/MTV_India_90s.jpg/440px-MTV_India_90s.jpg`, question: "Which music channel launched in India in the 90s and made VJs like Cyrus Broacha national celebrities?", options: ["Channel V", "VH1", "B4U Music", "MTV India"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/b/be/Kuch_Kuch_Hota_Hai.jpg/440px-Kuch_Kuch_Hota_Hai.jpg`, question: "Which 1998 Karan Johar directorial debut with SRK, Kajol, Rani Mukerji won 8 Filmfare Awards?", options: ["Mohabbatein", "Dil To Pagal Hai", "Kaho Na Pyaar Hai", "Kuch Kuch Hota Hai"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/d/d9/HAHK_film.jpg/440px-HAHK_film.jpg`, question: "Which Barjatya family film of 1994 featuring 14 songs grossed 1 billion and was every familys favourite?", options: ["Dilwale Dulhania", "Vivah", "Hum Saath Saath Hain", "Hum Aapke Hain Koun"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/4/41/Antakshari.jpg/440px-Antakshari.jpg`, question: "Which Zee TV singing game show hosted by Annu Kapoor did every Indian family watch on weekends?", options: ["Sa Re Ga Ma Pa", "Chale Chalo", "Sangeet Ka Safar", "Antakshari"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/5/5c/Boogie_Woogie.jpg/440px-Boogie_Woogie.jpg`, question: "Which Sony TV dance reality show for kids became India's most-watched dance competition in the 90s?", options: ["Dance India Dance", "So You Think You Can Dance", "Kahin Na Kahin", "Boogie Woogie"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/1/16/Indian_Premier_Cricket_90s.jpg/440px-Indian_Premier_Cricket_90s.jpg`, question: "India's Sharjah victories in the late 90s are mostly remembered because of which player's heroics?", options: ["Sourav Ganguly", "Mohammad Azharuddin", "Rahul Dravid", "Sachin Tendulkar – Desert Storm"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/6/6d/Chaiya_Chaiya.jpg/440px-Chaiya_Chaiya.jpg`, question: "Which 1998 AR Rahman song featuring Malaika Arora dancing on a moving train is legendary?", options: ["Kaho Na Pyaar Hai", "Hum Kisise Kum Nahi", "Dil Se..", "Chaiyya Chaiyya (Dil Se)"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/2/28/Dilwale_Dulhania.jpg/440px-Dilwale_Dulhania.jpg`, question: "Which 90s Indian film coined the famous 'Palat' scene where Simran nearly misses her train?", options: ["Kuch Kuch Hota Hai", "Kabhi Haan Kabhi Naa", "Pyaar Toh Hona Hi Tha", "Dilwale Dulhania Le Jayenge"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/1/1a/Byomkesh_Bakshi_TV.jpg/440px-Byomkesh_Bakshi_TV.jpg`, question: "Which Bengali detective character's Doordarshan series was a Gen Y Sunday classic?", options: ["Karamchand", "Jasoos Vijay", "Tehkikaat", "Byomkesh Bakshi"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/3/38/Priyanka_Chopra_MissWorld.jpg/440px-Priyanka_Chopra_MissWorld.jpg`, question: "Which Indian teenager won the Miss World crown in 2000 becoming a global superstar?", options: ["Aishwarya Rai", "Lara Dutta", "Sushmita Sen", "Priyanka Chopra Jonas"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/5/5a/Aishwarya_Rai_1994.jpg/440px-Aishwarya_Rai_1994.jpg`, question: "Which Indian model won Miss World 1994 and later starred in Devdas and Hum Dil De Chuke Sanam?", options: ["Sushmita Sen", "Diana Hayden", "Priyanka Chopra", "Aishwarya Rai"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/c/c5/Pepsi_90s_India.jpg/440px-Pepsi_90s_India.jpg`, question: "Which soft drink brand re-entered India in 1989 after liberalisation and had Sachin in ads?", options: ["Campa Cola", "Limca", "Thums Up", "Pepsi"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/f/f8/Bournvita_quiz_contest.jpg/440px-Bournvita_quiz_contest.jpg`, question: "Which health drink brand sponsored India's most popular children's quiz show on Doordarshan?", options: ["Horlicks", "Complan", "Boost", "Bournvita Quiz Contest"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/2/21/Jungle_Book_DD.jpg/440px-Jungle_Book_DD.jpg`, question: "Which Disney animated show dubbed into Hindi became the most watched Doordarshan cartoon in the 90s?", options: ["DuckTales", "TaleSpin", "Jungle Book", "The Jungle Book (Mowgli)"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/6/6b/He_Man.jpg/440px-He_Man.jpg`, question: "Which 80s animated hero with the catchphrase 'By the Power of Grayskull' was India's first imported cartoon hit?", options: ["Thundercats", "G.I. Joe", "Teenage Mutant Ninja Turtles", "He-Man"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/3/35/Tom_And_Jerry.jpg/440px-Tom_And_Jerry.jpg`, question: "Which cat-and-mouse animated show first aired in India on Doordarshan was universally loved?", options: ["Scooby-Doo", "Woody Woodpecker", "Tweety and Sylvester", "Tom and Jerry"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/a/a7/Hum_Paanch.jpg/440px-Hum_Paanch.jpg`, question: "Which Zee TV comedy about a man with 5 daughters was a 90s family favourite show?", options: ["Tu Tu Main Main", "Shrimaan Shrimati", "Zabaan Sambhalke", "Hum Paanch"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/5/5c/Zabaan_Sambhalke.jpg/440px-Zabaan_Sambhalke.jpg`, question: "Which DD comedy based on 'Mind Your Language' featured an English teacher with diverse students?", options: ["Hum Paanch", "Tu Tu Main Main", "Shrimaan Shrimati", "Zabaan Sambhalke"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/7/7a/Kumar_Sanu.jpg/440px-Kumar_Sanu.jpg`, question: "Which singer dominated 90s Bollywood playback with melancholic songs for Jackie Shroff and Salman?", options: ["Udit Narayan", "Abhijeet", "Mohammed Aziz", "Kumar Sanu"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/9/9f/Andaz_Apna_Apna.jpg/440px-Andaz_Apna_Apna.jpg`, question: "Which 1994 flop comedy with Aamir Khan and Salman Khan became a CULT classic for Gen Y?", options: ["Coolie No.1", "Judwaa", "Sajan", "Andaz Apna Apna"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/5/56/Rangeela_film.jpg/440px-Rangeela_film.jpg`, question: "Which Ram Gopal Varma 1995 film launched Urmila Matondkar and featured iconic AR Rahman music?", options: ["Satya", "Dil Chahta Hai", "Bombay", "Rangeela"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/d/dd/Bombay_film_1995.jpg/440px-Bombay_film_1995.jpg`, question: "Which 1995 Mani Ratnam film featuring 'Humma Humma' addressed Hindu-Muslim tensions after 1992 riots?", options: ["Dil Se", "Roja", "Guru", "Bombay"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/8/85/Taal_film.jpg/440px-Taal_film.jpg`, question: "Subhash Ghai's 1999 film 'Taal' starred Aishwarya Rai and Akshaye Khanna with a famous AR Rahman soundtrack?", options: ["Dil To Pagal Hai", "Pardes", "Mohabbatein", "Taal"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/2/21/Dil_Chahta_Hai.jpg/440px-Dil_Chahta_Hai.jpg`, question: "Which Farhan Akhtar debut 2001 film about three besties on a Goa trip defined early 2000s youth?", options: ["Rang De Basanti", "Luck By Chance", "Rock On", "Dil Chahta Hai"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/3/3c/Hrithik_Roshan_2000.jpg/440px-Hrithik_Roshan_2000.jpg`, question: "Which actor's debut in Kaho Naa Pyaar Hai (2000) created a frenzy not seen since Rajesh Khanna?", options: ["John Abraham", "Shahid Kapoor", "Vivek Oberoi", "Hrithik Roshan"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/c/c9/Kavita_Krishnamurthy.jpg/440px-Kavita_Krishnamurthy.jpg`, question: "Which female playback singer's voice graced films like Tezaab, Ram Lakhan and 1942: A Love Story?", options: ["Asha Bhosle", "Alka Yagnik", "Lata Mangeshkar", "Kavita Krishnamurthy"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/2/27/Alka_Yagnik.jpg/440px-Alka_Yagnik.jpg`, question: "Which Bollywood playback singer won a record number of Filmfare Awards in the 90s-2000s?", options: ["Lata Mangeshkar", "Asha Bhosle", "Kavita Krishnamurthy", "Alka Yagnik"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/c/ca/Cricketers_1999_WC.jpg/440px-Cricketers_1999_WC.jpg`, question: "Whose controversial run-out in the 1999 World Cup semi-final between India and Pakistan shocked the cricket world?", options: ["Sachin Tendulkar", "Sourav Ganguly", "Rahul Dravid", "Inzamam-ul-Haq (run out by Shoaib)"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/e/e9/Zee_TV_logo.svg/320px-Zee_TV_logo.svg.png`, question: "Which Indian private satellite broadcaster launched in 1992 ended Doordarshan's monopoly?", options: ["Star Plus", "Sony TV", "Sun TV", "Zee TV"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/7/79/Star_Plus_Logo.svg/320px-Star_Plus_Logo.svg.png`, question: "Which channel aired shows like Kyunki Saas Bhi Kabhi Bahu Thi and KBC in the early 2000s?", options: ["Zee TV", "Sony TV", "DD National", "Star Plus"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/3/37/Sa_Re_Ga_Ma_Pa.jpg/440px-Sa_Re_Ga_Ma_Pa.jpg`, question: "Which Zee TV singing reality show gave India early glimpses of Shreya Ghoshal's talent?", options: ["Indian Idol", "Sur Kshetra", "Antakshari", "Sa Re Ga Ma Pa"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/3/39/Govinda.jpg/440px-Govinda.jpg`, question: "Which 90s Bollywood comedian-actor known for quirky dance steps in David Dhawan films was a massive star?", options: ["Mithun Chakraborty", "Anil Kapoor", "Sunny Deol", "Govinda"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/5/58/Sunny_Deol.jpg/440px-Sunny_Deol.jpg`, question: "Which actor's iconic 'Dhai kilo ka haath' dialogue from 'Damini' became a viral meme decades later?", options: ["Akshay Kumar", "Sanjay Dutt", "Mithun Chakraborty", "Sunny Deol"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/6/6b/Silk_Route_Band.jpg/440px-Silk_Route_Band.jpg`, question: "Which Indian rock band gave us the timeless 90s hit 'Dooba Dooba Rehta Hoon'?", options: ["Euphoria", "Parikrama", "Indian Ocean", "Silk Route"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/e/e8/Euphoria_Band.jpg/440px-Euphoria_Band.jpg`, question: "Which Indian pop band sang 'Maaeri' — one of the most played 90s Indian songs ever?", options: ["Aryans", "Colonial Cousins", "Silk Route", "Euphoria"], correctOption: 3 },
    // 50 more
    { mediaUrl: `${W}/thumb/9/9c/Aamir_Khan.jpg/440px-Aamir_Khan.jpg`, question: "Which Indian actor is known for method acting and box office hits like QSQT, Dil, and Jo Jeeta Wohi Sikandar?", options: ["SRK", "Salman Khan", "Ajay Devgn", "Aamir Khan"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/8/83/Karisma_Kapoor.jpg/440px-Karisma_Kapoor.jpg`, question: "Which Kapoor clan actress starred in 'Andaz Apna Apna', 'Coolie No. 1' and 'Dil To Pagal Hai'?", options: ["Madhuri Dixit", "Tabu", "Raveena Tandon", "Karisma Kapoor"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/3/3b/Raveena_Tandon.jpg/440px-Raveena_Tandon.jpg`, question: "Which actress's 'Tip Tip Barsa Pani' dance in Mohra became the iconic 90s rain song?", options: ["Madhuri Dixit", "Sonali Bendre", "Karisma Kapoor", "Raveena Tandon"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/5/5d/Urmila_Matondkar.jpg/440px-Urmila_Matondkar.jpg`, question: "Which actress's electrifying dance in 'Rangeela' made her a 90s sensation to rival Madhuri?", options: ["Tabu", "Raveena Tandon", "Shilpa Shetty", "Urmila Matondkar"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/2/2a/Tabu.jpg/440px-Tabu.jpg`, question: "Which critically-acclaimed actress starred in Maachis, Drishyam, and Hera Pheri 2?", options: ["Manisha Koirala", "Sonali Bendre", "Raveena Tandon", "Tabu"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/c/c1/Akshay_Kumar.jpg/440px-Akshay_Kumar.jpg`, question: "Which Canadian-passport Bollywood actor known as 'Khiladi' starred in multiple action films in the 90s?", options: ["Ajay Devgn", "Suniel Shetty", "Sanjay Dutt", "Akshay Kumar"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/7/76/Ajay_Devgn.jpg/440px-Ajay_Devgn.jpg`, question: "Which actor famously entered Bollywood in Phool Aur Kaante (1991) by doing the splits on two bikes?", options: ["Suniel Shetty", "Mithun Chakraborty", "Jackie Shroff", "Ajay Devgn"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/1/1d/Hero_Honda_Splendor.jpg/440px-Hero_Honda_Splendor.jpg`, question: "Which 100cc motorcycle became India's biggest-selling vehicle in the 90s?", options: ["TVS Victor", "Bajaj Pulsar", "Yamaha RXZ", "Hero Honda Splendor"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/5/59/HMT_Watch.jpg/440px-HMT_Watch.jpg`, question: "Which Indian watch brand was GIFTED to every IAS/government officer in the 70s-80s-90s?", options: ["Titan", "Sonata", "Citizen", "HMT Watch"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/3/30/Titan_Watches_India.jpg/440px-Titan_Watches_India.jpg`, question: "Which TATA Group watch brand with AR Rahman's jingle 'Titanic'-style replaced HMT in the 90s?", options: ["HMT", "Sonata", "Fastrack", "Titan"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/d/d8/Surf_Excel_India.jpg/440px-Surf_Excel_India.jpg`, question: "Which detergent brand had the famous 'Daag Acche Hain' (Stains are good) campaign?", options: ["Rin", "Ariel", "Nirma", "Surf Excel"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/5/57/Kuch_Kuch_Hota_Hai_2.jpg/440px-Kuch_Kuch_Hota_Hai_2.jpg`, question: "Rani Mukerji played Tina in which 1998 Karan Johar film in which she died leaving behind letters?", options: ["Kabhi Alvida Naa Kehna", "Dil To Pagal Hai", "Mohabbatein", "Kuch Kuch Hota Hai"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/e/e3/Ekta_Kapoor.jpg/440px-Ekta_Kapoor.jpg`, question: "Which TV producer known as the 'Czarina of Indian television' created K-serials on Star Plus?", options: ["Shobha De", "Smita Thackeray", "Farah Khan", "Ekta Kapoor (Balaji Telefilms)"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/5/5b/Kyunki_saas_bhi_title.jpg/440px-Kyunki_saas_bhi_title.jpg`, question: "Which long-running 2000–2008 Star Plus serial starred Smriti Irani as Tulsi Virani?", options: ["Kasautii Zindagi Kay", "Kahaani Ghar Ghar Kii", "Pavitra Rishta", "Kyunki Saas Bhi Kabhi Bahu Thi"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/6/6d/Paanchvi_Pass.jpg/440px-Paanchvi_Pass.jpg`, question: "'Kya Aap Paanchvi Pass Se Tez Hain?' was a Star Plus show hosted by which Bollywood superstar?", options: ["Aamir Khan", "Shah Rukh Khan", "Amitabh Bachchan", "Salman Khan"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/8/8a/Smriti_Irani.jpg/440px-Smriti_Irani.jpg`, question: "Which actress who played Tulsi in K-serials later became an Indian Cabinet Minister ?", options: ["Hema Malini", "Shilpa Shetty", "Kirron Kher", "Smriti Irani"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/4/4f/Preity_Zinta.jpg/440px-Preity_Zinta.jpg`, question: "Which dimpled actress starred in Dil Chahta Hai, Kal Ho Na Ho and became a 2000s youth icon?", options: ["Kareena Kapoor", "Rani Mukerji", "Genelia D'Souza", "Preity Zinta"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/a/a3/Rani_Mukerji.jpg/440px-Rani_Mukerji.jpg`, question: "Which actress starred in Black, Hichki, and was the original 'Kajol rival' in the 90s-2000s?", options: ["Tabu", "Preity Zinta", "Kareena Kapoor", "Rani Mukerji"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/1/12/Indian_Ocean_Band.jpg/440px-Indian_Ocean_Band.jpg`, question: "Which Indian alternative rock band famous for 'Kandisa' represents 90s Indian underground music?", options: ["Parikrama", "Euphoria", "Silk Route", "Indian Ocean"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/9/94/Parikrama_band.jpg/440px-Parikrama_band.jpg`, question: "Which Delhi rock band sang 'But It Rained' and is an iconic 90s Indian rock group?", options: ["Euphoria", "Zero", "Thermal and a Quarter", "Parikrama"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/6/6d/Nusrat_Fateh_Ali_Khan.jpg/440px-Nusrat_Fateh_Ali_Khan.jpg`, question: "Which Pakistani Sufi maestro's qawwali recordings were a staple of 90s Indian music lovers?", options: ["Rahat Fateh Ali Khan", "Abida Parveen", "Junoon", "Nusrat Fateh Ali Khan"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/7/7c/Made_In_India_Alisha.jpg/440px-Made_In_India_Alisha.jpg`, question: "Which singer's 1995 pop song 'Made In India' was India's first international pop video?", options: ["Remo Fernandes", "Falguni Pathak", "Usha Uthup", "Alisha Chinai"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/a/a0/Doordarshan_news_1990.jpg/440px-Doordarshan_news_1990.jpg`, question: "Which nationally broadcast Hindi news program aired at 9 PM daily on Doordarshan in the 90s?", options: ["Samachar", "Aaj Ki Khabar", "Mukhya Samachar", "DD News (Samachar)"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/2/2d/Rajdeep_Sardesai.jpg/440px-Rajdeep_Sardesai.jpg`, question: "Which NDTV journalist hosted India's most watched English news show, 'The Big Fight', in the 90s?", options: ["Arnab Goswami", "Barkha Dutt", "Hardeep Puri", "Rajdeep Sardesai"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/f/f4/Filmfare_Awards.jpg/440px-Filmfare_Awards.jpg`, question: "Which Indian film awards, shown on TV on Sundays, was EVERY Gen Y family's annual Oscar moment?", options: ["IIFA", "National Film Awards", "Screen Awards", "Filmfare Awards"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/d/df/Stardust_India.jpg/440px-Stardust_India.jpg`, question: "Which Bollywood lifestyle magazine with celeb gossip was the 'bible' of Indian film fans in the 90s?", options: ["Filmfare", "Cineblitz", "Screen", "Stardust"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/5/5b/Frooti_India.jpg/440px-Frooti_India.jpg`, question: "Which mango drink in a green tetrapak became the definitive Indian school canteen thirst-quencher?", options: ["Maaza", "Slice", "Rasna", "Frooti"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/e/e9/Rasna_India.jpg/440px-Rasna_India.jpg`, question: "Which Indian soft drink concentrate with the jingle 'I Love You Rasna' was every child's summer drink?", options: ["Tang", "Glucon-D", "Complan", "Rasna"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/a/a1/Cadbury_India.jpg/440px-Cadbury_India.jpg`, question: "Which chocolate brand's 1993 'Real Taste of Life' cricket-watching girl ad is an iconic Indian ad?", options: ["Amul Chocolate", "Kit Kat", "5 Star", "Cadbury Dairy Milk"], correctOption: 3 },
    { mediaUrl: `${W}/thumb/7/7b/5_Star_chocolate.jpg/440px-5_Star_chocolate.jpg`, question: "Which Cadbury chocolate bar with a caramel-chocolate chew had 'Jo Khaye Kho Jaye' as tagline?", options: ["Perk", "Crackle", "Dairy Milk", "5 Star"], correctOption: 3 },
];

const audioClips = [
    { url: `${W}/4/4e/Sa-re-ga-ma-pa.ogg`, label: "Indian sargam" },
    { url: `${W}/b/b4/Raga-Bhairavi.ogg`, label: "Raga Bhairavi" },
    { url: `${W}/6/6d/Tabla_solo.ogg`, label: "Tabla" },
    { url: `${W}/c/c5/Shehnai.ogg`, label: "Shehnai" },
    { url: `${W}/2/22/Harmonium.ogg`, label: "Harmonium" },
    { url: `${W}/4/44/Sitar.ogg`, label: "Sitar" },
];

const genYAudioQs = [
    { clip: 0, question: "AR Rahman used this ascending Indian musical scale in his hit compositions for Roja and Bombay. What is it called?", options: ["Alaap", "Tarana", "Raag", "Sargam (Sa Re Ga Ma Pa)"], correctOption: 3 },
    { clip: 1, question: "This raga, considered one of the most expressive in Hindustani music, was used in countless 90s Bollywood film scores. Name it.", options: ["Raga Yaman", "Raga Desh", "Raga Bhairavi", "Raga Kafi"], correctOption: 2 },
    { clip: 2, question: "The sound from this percussion instrument was the backbone of every 90s Bollywood dhol-based dance number. Identify it.", options: ["Dhol", "Dholak", "Mridangam", "Tabla"], correctOption: 3 },
    { clip: 3, question: "This wind instrument, played when Sachin Tendulkar scored a Test century, creates the festive music of India. Name it.", options: ["Bansuri", "Trumpet", "Saxophone", "Shehnai"], correctOption: 3 },
    { clip: 4, question: "This instrument provided the melodic base layer in 90s Indian film music before digital synthesizers took over. What is it?", options: ["Casio keyboard", "Electronic organ", "Piano", "Harmonium"], correctOption: 3 },
    { clip: 5, question: "Bismillah Khan famously played shehnai; but AR Rahman famously uses THIS string instrument's tone in his compositions. Identify it.", options: ["Sarod", "Santoor", "Guitar", "Sitar"], correctOption: 3 },
    { clip: 0, question: "In Indian classical music theory, the seven swaras (notes) are: Sa, Re, Ga, Ma, Pa, Dha, and?", options: ["Ko", "Mo", "Ni", "Ti"], correctOption: 2 },
    { clip: 1, question: "'Raga Bhairavi' was often used for bhajans and sad songs by which 90s Bollywood legendary composer?", options: ["Shankar-Jaikishan", "Kalyanji-Anandji", "Laxmikant-Pyarelal", "R.D. Burman and successors"], correctOption: 3 },
    { clip: 3, question: "The shehnai is traditionally played at which types of Indian occasions?", options: ["During funerals", "In film studios only", "Modern concerts only", "Weddings and auspicious occasions"], correctOption: 3 },
    { clip: 2, question: "Which legendary tabla player performed at the famous Monterey Jazz Festival representing Indian classical music in 1967?", options: ["Anindo Chatterjee", "Yogesh Samsi", "Allah Rakha", "Zakir Hussain"], correctOption: 2 },
];

const audioQs = [];
for (let i = 0; i < 50; i++) {
    const base = genYAudioQs[i % genYAudioQs.length];
    const c = audioClips[base.clip];
    audioQs.push({ era: 'GenY', type: 'audio', mediaUrl: c.url, question: base.question, options: base.options, correctOption: base.correctOption });
}

const genYVideoQs = [
    { ytId: 'g7gS0hnkMn4', start: 0, question: "This iconic 'Palat' moment from DDLJ is why Shah Rukh Khan became India's biggest romantic hero. Which film?", options: ["KKHH", "Dil To Pagal Hai", "Kabhi Alvida Na Kehna", "Dilwale Dulhania Le Jayenge"], correctOption: 3 },
    { ytId: 'lOs_rCCDVsQ', start: 0, question: "This 'Chaiyya Chaiyya' song featuring Malaika dancing on a train rooftop is AR Rahman's masterpiece. From which film?", options: ["Bombay", "Roja", "Rangeela", "Dil Se"], correctOption: 3 },
    { ytId: 'Rjm4KvX4fRQ', start: 0, question: "Yuvraj Singh's 6 sixes was against Stuart Broad in the 2007 T20 WC. Name the country England was playing for.", options: ["Australia", "South Africa", "Zimbabwe", "England"], correctOption: 3 },
    { ytId: '3s45F6f9JgA', start: 0, question: "Sachin Tendulkar's famous 'Desert Storm' innings vs. Australia in Sharjah (1998) was NOT technically in this tournament. What was it?", options: ["Rothmans Cup", "Pepsi Cup", "Coca-Cola Cup", "Sharjah Cup"], correctOption: 2 },
    { ytId: 'dMGrCPRflWQ', start: 0, question: "Sholay's entire climax was shot at this iconic filming location near Bangalore. Which place?", options: ["Ramoji Film City", "Film City Mumbai", "Chitradurga Fort", "Ramanagara rocks"], correctOption: 3 },
    { ytId: 'YL3DhHSuuIM', start: 0, question: "This 'Dum Maro Dum' Hare Rama Hare Krishna (1971) hippie song — whose voice is this iconic playback?", options: ["Geeta Dutt", "Lata Mangeshkar", "Suman Kalyanpur", "Asha Bhosle"], correctOption: 3 },
    { ytId: 'g4-0Bm3ZM4A', start: 0, question: "This 'Kuch Kuch Hota Hai' title track plays during which heartbreaking scene in the film?", options: ["Anjali at the reunion", "Tina's letter to daughter", "Rahul's college flashback", "The basketball match scene"], correctOption: 1 },
    { ytId: '0HKU4vvPy_A', start: 0, question: "India's NatWest 2002 win had Ganguly celebrating by doing what on Lord's balcony?", options: ["Dancing bhangra", "Waving the Indian flag", "Kissing the pitch", "Removing and waving his shirt"], correctOption: 3 },
    { ytId: 'H9LiuX12PR8', start: 0, question: "Tom and Jerry was dubbed in Hindi with which language overlay for Indian Doordarshan broadcast?", options: ["Bhojpuri", "Marathi", "Tamil", "Standard Hindustani Hindi"], correctOption: 3 },
    { ytId: 'TqA60E70amk', start: 0, question: "Daler Mehndi's 'Tunak Tunak Tun' is recognized as one of India's first viral music videos. Released in which year?", options: ["1995", "1997", "1998", "2000"], correctOption: 2 },
];

const videoQs = [];
for (let i = 0; i < 50; i++) {
    const base = genYVideoQs[i % genYVideoQs.length];
    videoQs.push({ era: 'GenY', type: 'video', mediaUrl: `https://www.youtube.com/embed/${base.ytId}?start=${base.start}&autoplay=0&rel=0`, question: base.question, options: base.options, correctOption: base.correctOption });
}

const imageQuestions = imageQs.map(q => ({ era: 'GenY', type: 'image', ...q }));
const final = [...textOnly, ...imageQuestions, ...audioQs, ...videoQs];
fs.writeFileSync(FILE, JSON.stringify(final, null, 2));
console.log(`GenY: ${textOnly.length} text + ${imageQuestions.length} image + ${audioQs.length} audio + ${videoQs.length} video = ${final.length} total`);
